# Generated by Django 5.0.7 on 2024-07-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='developer',
            index=models.Index(fields=['title'], name='developers__title_0428ce_idx'),
        ),
    ]
