# Generated by Django 5.0.7 on 2024-07-16 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0002_developer_developers__title_0428ce_idx'),
        ('developers', '0002_developer_inn'),
    ]

    operations = [
    ]
