# Generated by Django 5.0.7 on 2024-07-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('developers', '0004_developer_rating'), ('developers', '0005_alter_developer_rating'), ('developers', '0006_alter_developer_rating')]

    dependencies = [
        ('developers', '0003_merge_20240716_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='rating',
            field=models.FloatField(default=0.0, verbose_name='Рейтинг'),
        ),
    ]
