# Generated by Django 5.0.7 on 2024-07-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0003_merge_20240716_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Рейтинг'),
        ),
    ]
