# Generated by Django 5.0.7 on 2024-07-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0004_developer_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='rating',
            field=models.SmallIntegerField(default=0, verbose_name='Рейтинг'),
        ),
    ]
