# Generated by Django 5.0.7 on 2024-07-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0005_alter_developer_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='rating',
            field=models.FloatField(default=0.0, verbose_name='Рейтинг'),
        ),
    ]
