# Generated by Django 5.0.7 on 2024-07-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=32, verbose_name='Артикул')),
                ('area', models.FloatField(verbose_name='Площадь')),
                ('price', models.IntegerField(blank=True, default=0, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
                'indexes': [models.Index(fields=['article'], name='realty_flat_article_f5f3ca_idx')],
            },
        ),
    ]
