# Generated by Django 5.0.7 on 2024-07-15 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0001_initial'),
        ('realty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='developer',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='flats',
                to='developers.developer',
                verbose_name='Застройщик',
            ),
        ),
    ]
